/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNIDemo */

#ifndef _Included_JNIDemo
#define _Included_JNIDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNIDemo
 * Method:    java_hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNIDemo_java_1hello
  (JNIEnv *, jobject);

/*
 * Class:     JNIDemo
 * Method:    sum
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_JNIDemo_sum
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     JNIDemo
 * Method:    exchangeString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JNIDemo_exchangeString
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
