/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNIDemo */

#ifndef _Included_JNIDemo
#define _Included_JNIDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNIDemo
 * Method:    java_hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNIDemo_java_1hello
  (JNIEnv *, jobject);

/*
 * Class:     JNIDemo
 * Method:    get_val
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_JNIDemo_get_1val
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
